[build]
  publish = "public"
  functions = "functions"
  environment = { GO_VERSION = "1.12" }
  command = "npm install && go mod download && cd go && go build -o ../functions/go-error ./... && cd .."
